import 'package:tsdm_client/constants/url.dart';

/// Whether [uri] is a relative link or an absolute link to the forum's own hosts on the default port.
///
/// Rejects other schemes, other hosts, user info and explicit ports so a link crafted by a user can never pass as
/// one generated by the forum.
bool isForumUri(Uri uri) {
  if (uri.hasScheme && uri.scheme != 'https' && uri.scheme != 'http') {
    return false;
  }
  if (uri.hasScheme || uri.hasAuthority) {
    if (uri.host != baseHost && uri.host != baseHostAlt) {
      return false;
    }
    if (uri.userInfo.isNotEmpty || uri.hasPort) {
      return false;
    }
  }
  // Relative paths are resolved against the forum root: only a bare file name or a root path is accepted.
  final path = uri.path;
  return !path.contains('..') && !path.contains('//');
}

/// Whether [uri] is a forum link (see [isForumUri]) to exactly the script [file], e.g. `home.php`.
///
/// `evilhome.php`, `x/home.php` and `home.php/x` are not.
bool isForumScript(Uri uri, String file) =>
    isForumUri(uri) && uri.pathSegments.length == 1 && uri.pathSegments.single == file;

/// Query parameters of [uri], null when they are malformed (bad percent encoding).
Map<String, String>? safeQueryParameters(Uri uri) {
  try {
    return uri.queryParameters;
  } on FormatException {
    return null;
  }
}

final _spaceUidRe = RegExp(r'^space-uid-(\d+)\.html$');

/// Uid in a forum profile link [href] (`home.php?mod=space&uid=N`, maybe relative), null for anything else.
///
/// Only the forum's own host and the exact `home.php` path are accepted; `space-uid-N.html` rewrite links too.
int? uidOfProfileUrl(String? href) {
  if (href == null || href.isEmpty) {
    return null;
  }
  final uri = Uri.tryParse(href.replaceAll('&amp;', '&'));
  if (uri == null || !isForumUri(uri)) {
    return null;
  }
  if (isForumScript(uri, 'home.php')) {
    final q = safeQueryParameters(uri);
    if (q == null || q['mod'] != 'space') {
      return null;
    }
    final uid = int.tryParse(q['uid'] ?? '');
    return uid != null && uid > 0 ? uid : null;
  }
  final m = uri.pathSegments.length == 1 ? _spaceUidRe.firstMatch(uri.pathSegments.single) : null;
  if (m != null) {
    final uid = int.tryParse(m.group(1)!);
    return uid != null && uid > 0 ? uid : null;
  }
  return null;
}
