/// Default cookie expiration time in seconds.
///
/// This is kept the same with server behavior.
const defaultCookieTime = 2592000;

/// Host in url.
const baseHost = 'www.tsdm39.com';

/// Host in url, without www prefix.
const baseHostAlt = 'tsdm39.com';

/// Server site base url.
const baseUrl = 'https://$baseHost';

/// Homepage of tsdm.
const homePage = '$baseUrl/forum.php';

/// Page to register new account
const signUpPage = '$baseUrl/member.php?mod=register.php';

/// User profile page for user with given uid.
const uidProfilePage = '$baseUrl/home.php?mod=space&uid=';

/// User profile page for user with given username.
const usernameProfilePage = '$baseUrl/home.php?mod=space&username=';

/// Default fallback user avatar url when user avatar is unavailable.
const noAvatarUrl = '$baseUrl/uc_server/images/noavatar_middle.gif';

/// Build the url of the avatar image the forum stores for the user with [uid].
///
/// Pages that render a user card carry the avatar url in their html (`<img class="_avt user_avatar" data-src="...">`),
/// but list pages do not: a thread row in a forum only has the author's name and uid, so the url has to be built from
/// the uid there. This is the rule the forum's own script uses (`static/js/common.js`, function `loadAvatar`): pad the
/// uid to nine digits, split it into three directory levels of 3, 2 and 2 digits and name the file after the last two
/// digits.
///
/// ```text
/// uid 7       -> https://www.tsdm39.com/data/avatar/000/00/00/07_avatar_middle.jpg
/// uid 1234567 -> https://www.tsdm39.com/data/avatar/001/23/45/67_avatar_middle.jpg
/// ```
///
/// Of the three sizes the server generates (`small` 48x48, `middle` 140x140 and `big` 200x200) this uses `middle`,
/// which is the one thread pages use, so the avatar loaded for a thread row is the very same cache entry the thread
/// page needs later, and it still has enough pixels for the avatar circle on a high density screen.
///
/// Returns null when [uid] is not a positive integer, which is the case for anonymous and deleted authors: they keep
/// the text placeholder in the avatar circle.
///
/// Only avatars uploaded to the forum have a file here. A user who set an external avatar url instead has none and the
/// request answers 404, exactly like on the forum's own pages, where the script then falls back to the default avatar.
String? avatarUrlOfUid(String? uid) {
  if (uid == null) {
    return null;
  }
  final id = int.tryParse(uid);
  if (id == null || id <= 0) {
    return null;
  }
  final padded = '$id'.padLeft(9, '0');
  return '$baseUrl/data/avatar/${padded.substring(0, 3)}/${padded.substring(3, 5)}/${padded.substring(5, 7)}/'
      '${padded.substring(7)}_avatar_middle.jpg';
}

/// Notice page of current logged user.
const noticeUrl = '$baseUrl/home.php?mod=space&do=notice';

/// All read notice page of current logged user.
const readNoticeUrl = '$baseUrl/home.php?mod=space&do=notice&isread=1';

/// Private personal messages.
const personalMessageUrl = '$baseUrl/home.php?mod=space&do=pm&filter=privatepm';

/// Broadcast messages.
const broadcastMessageUrl = '$baseUrl/home.php?mod=space&do=pm&filter=announcepm';

/// Broadcast message detail page.
const broadcastMessageDetailUrl = '$baseUrl/home.php?mod=space&do=pm&subop=viewg&pmid=';

/// The Discuz! built-in guide index page (`forum.php?mod=guide&view=index`).
///
/// Lists the four guide modules 最新热门 (hot), 最新精华 (digest), 最新回复 (new) and 最新发表 (newthread) with a few
/// threads each, plus a nav row that also links 抢沙发 (sofa). Visible to guests as well.
const guideIndexUrl = '$baseUrl/forum.php?mod=guide&view=index';

/// Url of the full guide list page for [view]: `hot`, `digest`, `new`, `newthread` or `sofa`.
String guideUrl(String view) => '$baseUrl/forum.php?mod=guide&view=$view';

/// Page contains all thread published by current logged user.
const myThreadThreadUrl = '$baseUrl/home.php?mod=space&do=thread&view=me&type=thread';

/// Page contains all posts (as replies in threads) published by current logged
/// user.
const myThreadReplyUrl = '$baseUrl/home.php?mod=space&do=thread&view=me&type=reply';

/// Page contains credential information of current user.
///
/// This page is also used for checking logged user info because it has the
/// complete information of current user:
/// * Username.
/// * Uid.
/// * Email address.
const modifyUserCredentialUrl = '$baseUrl/home.php?mod=spacecp&ac=profile&op=password';

/// Use [modifyUserCredentialUrl] to check user status.
///
/// This page contains full user info:
/// * Username
/// * UID
/// * User email
const String checkAuthenticationStateUrl = modifyUserCredentialUrl;

/// Url to get the latest app on Github.
const upgradeGithubReleaseUrl = 'https://github.com/Carinoasd/tsdm_client/releases/latest';

/// Url of the JSON file describing the latest published version.
///
/// The file lives in the repository root (`version.json`), is regenerated by `scripts/write_version_json.dart` on
/// every release and has the shape of `LatestVersionInfo`: `{"version": "1.18.0", "versionCode": 65, "changelog": ...}`.
const upgradeVersionInfoUrl = 'https://raw.githubusercontent.com/Carinoasd/tsdm_client/master/version.json';

/// Target url to post a reply to thread [tid], forum [fid].
String formatReplyThreadUrl(String fid, String tid) {
  return '$homePage?mod=post&action=reply&fid=$fid&tid=$tid&'
      'extra=&replysubmit=yes&infloat=yes&handlekey=fastpost&inajax=1';
}

/// Prefix in url to get fast reply window to a certain post.
const replyPostWindowSuffix = '&infloat=yes&handlekey=reply&inajax=1&ajaxtarget=fwin_content_reply';

/// Url of images have rendering issue with Impeller.
///
/// The root cause is not clear, maybe corrupt cache content, but it works with skia backend so should not be it.
/// Since these images are now for redirect back purpose, we could handle them specially although we didn't intend to
/// do it before, we have to do it before the next upcoming stable release of Flutter in August, 2025.
const tmpImpellerWorkaroundUrls = [
  'https://$baseHost/static/image/common/back.gif',
  'https://$baseHostAlt/static/image/common/back.gif',
];

/// Target url to post a reply to another post in thread [tid], forum [fid].
String formatReplyPostUrl(String fid, String tid) {
  return '$homePage?mod=post&infloat=yes&action=reply&fid=$fid&'
      'extra=&tid=$tid&replysubmit=yes&inajax=1';
}

/// Target url to get the dialog showing before purchasing a thread.
/// Need thread id [tid] and post id [pid].
String formatPurchaseDialogUrl(String tid, String pid) {
  return '$homePage?mod=misc&action=pay&tid=$tid&pid=$pid&infloat=yes&'
      'handlekey=pay&inajax=1&ajaxtarget=fwin_content_pay';
}

/// Target url to get the chat dialog with user [uid].
///
/// [dateRange] is a query parameter controlling history chat message to
/// display.
/// However we do not know the detail effect so keep it with it's default value
/// 2.
///
/// There are two kinds of dialog:
///
/// * Pure dialog, query parameter contains "infloat=1" from user profile page.
/// * Dialog embedded in page, does not have "infloat=1" query parameter, from
///   hover dialog on user brief profile in thread floor.
///
/// The former kind is wrapped in xml data, pure and have anything we want.
/// So we convert the later kind of url into the former format, which means:
///
/// For all url contains "handlekey=showmesg_$uid", "touid=$uid" and the uid are
/// the same, convert into the format returned by this function.
String formatChatUrl(String uid, {int dateRange = 2}) {
  return '$baseUrl/home.php?mod=spacecp&ac=pm&op=showmsg&'
      'handlekey=showmsg_$uid&touid=$uid&pmid=0&daterange=$dateRange&'
      'infloat=yes&inajax=1&ajaxtarget=fwin_content_showMsgBox';
}

/// Target url to get the chat full history page with user [uid].
///
/// Each page contains 10 messages.
String formatChatFullHistoryUrl(String uid, {int? page}) {
  return '$baseUrl/home.php?mod=space&do=pm&subop=view&touid=$uid'
      '${page != null ? '&page=$page' : ''}#last';
}

/// Target url to get xml data wrapping recent chat history data with user
/// [uid].
///
/// Use [dateRange] if we need longer ago chat history but as said above, we do
/// NOT know the real effect so keep it the default value in most situations.
///
/// The date in this page only contains recent history, without required values
/// to send a new message.
String formatChatRecentHistoryUrl(String uid, {int dateRange = 2}) {
  return '$baseUrl/home.php?mod=spacecp&ac=pm&op=showmsg&'
      'msgonly=1&touid=$uid&pmid=0&inajax=1&daterange=$dateRange';
}

/// Target url to send a message to another user.
///
/// This is mainly used in chat dialog in server, so use this in the same
/// situation.
String formatSendMessageUrl(String touid) {
  return '$baseUrl/home.php?mod=spacecp&ac=pm&op=send&touid=$touid&inajax=1';
}
