import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:tsdm_client/constants/layout.dart';
import 'package:tsdm_client/extensions/string.dart';
import 'package:tsdm_client/i18n/strings.g.dart';
import 'package:tsdm_client/routes/screen_paths.dart';
import 'package:tsdm_client/utils/logger.dart';
import 'package:tsdm_client/widgets/app_surface.dart';
import 'package:tsdm_client/widgets/custom_alert_dialog.dart';
import 'package:tsdm_client/widgets/heroes.dart';
import 'package:tsdm_client/widgets/single_line_text.dart';

/// Dialog for user operations.
class UserOperationDialog extends StatelessWidget with LoggerMixin {
  /// Constructor.
  const UserOperationDialog({
    required this.username,
    required this.avatarUrl,
    required this.heroTag,
    required this.latestThreadUrl,
    super.key,
  });

  /// Username
  final String username;

  /// User avatar url.
  ///
  /// Can be null.
  final String? avatarUrl;

  /// Tag for user avatar hero.
  final String heroTag;

  /// Url of latest thread page.
  ///
  /// The latest thread url is a dynamic url generated by server.
  final String? latestThreadUrl;

  /// A row of the menu: icon, title, rounded ink; closes the menu and opens [screen].
  Widget _entry(BuildContext context, IconData icon, String title, String screen) => ListTile(
    leading: Icon(icon),
    title: Text(title),
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(appInnerRadius)),
    trailing: const Icon(Icons.chevron_right),
    onTap: () async {
      context.pop();
      await context.pushNamed(screen);
    },
  );

  @override
  Widget build(BuildContext context) {
    // Expected containing two pairs of nodes:
    //
    // 1. My thread.
    // 2. Latest thread.

    final tr = context.t.homepage.welcome;
    final divider = Divider(
      height: 9,
      indent: 16,
      endIndent: 16,
      color: Theme.of(context).colorScheme.outlineVariant.withValues(alpha: 0.6),
    );

    return CustomAlertDialog.sync(
      title: Row(
        children: [
          HeroUserAvatar(username: username, avatarUrl: avatarUrl, heroTag: username, minRadius: 30),
          sizedBoxW12H12,
          Expanded(
            child: SingleLineText(
              username,
              style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
      // Same entries and order as before, grouped: the account itself, then threads, then the account list.
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          _entry(context, Icons.person_outline, context.t.profilePage.title, ScreenPaths.profile),
          _entry(context, Icons.military_tech_outlined, context.t.medalTitleHub.title, ScreenPaths.medalTitleHub),
          divider,
          _entry(context, Icons.history_outlined, tr.history, ScreenPaths.threadVisitHistory),
          _entry(context, Icons.article_outlined, tr.myThread, ScreenPaths.myThread),
          _entry(context, Icons.star_outline, tr.favorite, ScreenPaths.favorite),
          // Switching or adding an account was only reachable through the settings page (#16).
          _entry(context, Icons.manage_accounts_outlined, context.t.manageAccountPage.title, ScreenPaths.manageAccount),
          ListTile(
            leading: const Icon(Icons.update_outlined),
            title: Text(tr.latestThread),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(appInnerRadius)),
            trailing: latestThreadUrl == null ? null : const Icon(Icons.chevron_right),
            onTap: latestThreadUrl == null
                ? null
                : () async {
                    final target = latestThreadUrl!.parseUrlToRoute();
                    if (target == null) {
                      error('invalid kahrpba link: $latestThreadUrl');
                      return;
                    }
                    context.pop();
                    await context.pushNamed(
                      target.screenPath,
                      pathParameters: target.pathParameters,
                      queryParameters: target.queryParameters,
                    );
                  },
          ),
        ],
      ),
    );
  }
}
