name: My Build Android & Windows
on:
  workflow_dispatch:

env:
  CI_FLUTTER_VERSION: '3.41.1' # 对方更新后记得检查版本号
  CI_RUST_VERSION: "1.83.0" # 对方更新后记得检查版本号

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.CI_FLUTTER_VERSION }}
          cache: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.CI_RUST_VERSION }}

      - name: decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | tr -d '\r' | base64 --decode > android/app/upload-keystore.jks
        shell: bash

      - name: write key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties
        shell: bash

      - run: flutter pub get
      - run: dart run build_runner build --release --delete-conflicting-outputs
      - run: flutter build apk --release --target-platform android-arm64,android-x64

      - name: upload signed apk
        uses: actions/upload-artifact@v4
        with:
          name: signed-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.CI_FLUTTER_VERSION }}
          cache: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.CI_RUST_VERSION }}

      - run: flutter pub get
      - run: dart run build_runner build --release --delete-conflicting-outputs
      - run: flutter build windows --release
      - name: zip windows release
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath windows-app.zip
      - name: upload windows zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-zip
          path: windows-app.zip

  create-draft-release:
    needs: [android, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Generate draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: 手动构建版本
          draft: true
          files: |
            signed-android-apk/app-release.apk
            windows-build-zip/windows-app.zip
